Добавляет разметку главной страницы
htmlacademy-htmlcss/2022605-sedona-33 pull request #2
Opened 2022-02-06 19:19 UTC by Artem-Olkhovoi

2022-02-07 19:10 UTC, dean992008 requested changes

2022-02-07 19:10 UTC, dean992008 commented on index.html
> +  <img class="logo" src="" alt="Логотип курортного города Седона">
Логотип должен быть сылкой.

2022-02-07 19:10 UTC, dean992008 commented on index.html
> +  <nav class="main-navigation-header">
В `nav` должно быть обернуто только главное меню, поэтому я бы обернул только меню, без поиска избраного и т.д.

2022-02-07 19:10 UTC, dean992008 commented on index.html
> +        </span>
У открывающего и закрывающего элеммента должен быть одинаковый отступ от начала строки. 
Выполни автоформатирование чтобы это исправить.

2022-02-07 19:10 UTC, dean992008 commented on index.html
> +     <img class="main-banner" src="" alt="Основной баннер сайта города Седона">
Главный баннер и текст я бы тоже обернул в секцию.

2022-02-07 19:10 UTC, dean992008 commented on index.html
> +              <p class="advantages-description">— №1 —</p>
Полоски вокруг номера лучше убрать, мы из сделаем с помощью css

2022-02-07 19:10 UTC, dean992008 commented on index.html
> +          <li class="sub-advantages-item">
Жильё, Еда и Сувениры я бы вынес в отдельный список и поместил этот список в ли в конце текущего списка. 
Позже с помощью CSS визуально он разместиться как в макете.

2022-02-07 19:10 UTC, dean992008 commented on index.html
> +        <h2 class="main-index-appointment-title">Заинтересовались?</h2>
h2 здесь не описывает суть блока. Лучше сделать h2 скрытим, а `Заинтересовались?` с помощью `p`

2022-02-07 19:10 UTC, dean992008 commented on index.html
> +        <button class="main-index-appointment-button">
Не может быть сылки внутри кнопки, должна быть или сылка или кнопка, в данном случае это ссылка.

2022-02-07 19:10 UTC, dean992008 commented on index.html
> +        <img class="newsletter-background" src="">
Фон нужно будет сделать через CSS, поэтому тег здесь лишний.

2022-02-07 19:10 UTC, dean992008 commented on index.html
> +           <a class="footer-social-button" href="https://twitter.com/htmlacademy_ru">
Ссылки на стороние сайты должны открываться на новой вкладке.

2022-02-07 19:10 UTC, dean992008 commented on index.html
> +     <section class="footer-social">
Не уверез что секции в футере это хорошая идея, в них слишком мало контента.

2022-02-08 22:04 UTC, Artem-Olkhovoi commented on index.html
> +  <img class="logo" src="" alt="Логотип курортного города Седона">
Тоже думал про это. Показалось странным, что логотип с ссылкой на главную и рядом "Главная" тоже с ссылкой на главную.

2022-02-08 22:05 UTC, Artem-Olkhovoi commented on index.html
> +  <nav class="main-navigation-header">
вынес поиск, избранное и кнопку из nav

2022-02-08 22:06 UTC, Artem-Olkhovoi commented on index.html
> +        </span>
Сделал

2022-02-08 22:06 UTC, Artem-Olkhovoi commented on index.html
> +     <img class="main-banner" src="" alt="Основной баннер сайта города Седона">
Сделал

2022-02-08 22:06 UTC, Artem-Olkhovoi commented on index.html
> +              <p class="advantages-description">— №1 —</p>
Убрал

2022-02-08 22:08 UTC, Artem-Olkhovoi commented on index.html
> +          <li class="sub-advantages-item">
Вот тут не очень понял как надо сделать. Пока что просто перенёс их в самый конец списка

2022-02-08 22:08 UTC, Artem-Olkhovoi commented on index.html
> +        <h2 class="main-index-appointment-title">Заинтересовались?</h2>
Сделал

2022-02-08 22:08 UTC, Artem-Olkhovoi commented on index.html
> +        <button class="main-index-appointment-button">
Исправил

2022-02-08 22:08 UTC, Artem-Olkhovoi commented on index.html
> +        <img class="newsletter-background" src="">
Убрал

2022-02-08 22:09 UTC, Artem-Olkhovoi commented on index.html
> +           <a class="footer-social-button" href="https://twitter.com/htmlacademy_ru">
добавил атрибут target

2022-02-08 22:09 UTC, Artem-Olkhovoi commented on index.html
> +     <section class="footer-social">
тогда через div лучше? пока что сделал так

2022-02-09 08:50 UTC, dean992008 reviewed
Я могу принять только оба задания, поэтому поправь я прийму сразу 2.

2022-02-09 08:50 UTC, dean992008 commented on catalog.html
> +                    <a class="breadcrumbs-link" href="index.html"><img class="breadcrumbs-index-link" src=""></a>
Иконка это не контентная картинка, позже ее нужно будет добавить через CSS. Пока внутри ссылки нужно написать `Главная`

2022-02-09 08:50 UTC, dean992008 commented on catalog.html
> +                            <label class="control">
Здесь лучше использовать структуру, input + label(на томже урочне). Позже так будет гораздо удобнее сделать стилизовать.

2022-02-09 08:50 UTC, dean992008 commented on catalog.html
> +                    <img class="product-card-stars" src="">
Для звездочек сюда лучше добавить div а здездочки делать фоном, так мы сможем регулировать количество звезд.

2022-02-09 08:50 UTC, dean992008 commented on catalog.html
> +        <ol class="pagination">
Не вижу смыла использовать здесь ol, лучше ul

2022-02-09 08:50 UTC, dean992008 commented on catalog.html
> +            <option value="four">4</option>
Здесь можно добавить еще опций, 1, 2, 3, 5

2022-02-09 08:50 UTC, dean992008 commented on catalog.html
> +        <button class="button pagination-show-more" type="button">Загрузить ещё</button>
Это лучше сделать сылкой, если сломается js она не будет работать, а так можно хотя бы перебросить на 2 старницу

2022-02-09 08:50 UTC, dean992008 commented on index.html
> +        <li class="sub-advantages-item">
3 последних пункта нужно обернуть в li и ul, тоесть долна получиться структура: `ul>li>ul>li*3`

2022-02-09 17:01 UTC, Artem-Olkhovoi commented on catalog.html
> +                            <label class="control">
не совсем понял, что имеется ввиду

2022-02-09 17:04 UTC, dean992008 commented on catalog.html
> +                            <label class="control">
Переделать структура следующим образон: 
```html
<li class="catalog-filter-item">
  <input class="control-input" type="checkbox" name="swimming-pool" checked> 
  <label class="control">Бассейн</label>
</li>
```

2022-02-09 17:05 UTC, dean992008 commented on catalog.html
> +                            <label class="control">
P.S. `input + label` это CSS селектор, также так можно писать html а редактор будет разворачивать (погугли Emmet).

2022-02-09 17:10 UTC, Artem-Olkhovoi commented on catalog.html
> +                    <img class="product-card-stars" src="">
как это правильно сделать? вообще не понял

2022-02-09 17:18 UTC, dean992008 commented on catalog.html
> +                    <img class="product-card-stars" src="">
Пока просто div, когда дойдешь до CSS сделаешь звездочку фоном и добавишь `background-repeat: repeat-x` потом напишеш раскажу что дальше сделать?

2022-02-11 09:25 UTC, dean992008 commented on index.html
> +        <li class="sub-advantages-item">
Этот пункт сделан неправильно. Нужно будет созвонится я покажу.

2022-02-11 09:25 UTC, merged