Вносит визуализацию для элементов
htmlacademy-htmlcss/2022605-sedona-33 pull request #4
Opened 2022-02-20 12:09 UTC by Artem-Olkhovoi

2022-02-20 13:36 UTC, dean992008 requested changes

2022-02-20 13:36 UTC, dean992008 commented on styles/styles.css
> +body {
Нужно скопировать и добавить рекомендованых стили из критерия: http://joxi.ru/Vrwl1n1f7PGZ9m

2022-02-20 13:36 UTC, dean992008 commented on styles/styles.css
> +    font-family: "PT Sans";
Не коректные отступы в файле, нужно установить плагин editorconfig после чего выполнить автоматическое форматирование.

2022-02-20 13:36 UTC, dean992008 commented on styles/styles.css
> +    color: white;
Желательно везде использовать эдиный формати описания цвета (HEX)

2022-02-20 13:36 UTC, dean992008 commented on styles/styles.css
> +    padding-top: 17px;
Падинки можно написать в 1 свойстве
```
padding: 17px 16px;
```

2022-02-20 13:36 UTC, dean992008 commented on catalog.html
> +          <img class="logo" src="images\logo.svg" width="139" height="70" alt="Логотип курортного города Седона">
Не исправлено направление слешей в пути.

2022-02-20 13:36 UTC, dean992008 commented on catalog.html
> +              <img src="images\search-loop.svg" width="18.05" height="18.1">
Эти инокнки нужно убрать с ними будем работь позже.

2022-02-20 19:04 UTC, Artem-Olkhovoi commented on styles/styles.css
> +body {
сделал

2022-02-20 19:05 UTC, Artem-Olkhovoi commented on styles/styles.css
> +    padding-top: 17px;
сделал

2022-02-20 19:06 UTC, Artem-Olkhovoi commented on catalog.html
> +          <img class="logo" src="images\logo.svg" width="139" height="70" alt="Логотип курортного города Седона">
исправил автозаменой всех \ на / . Почему то при копировании пути файла через правую кнопку мыши копируется именно с \

2022-02-20 19:06 UTC, Artem-Olkhovoi commented on catalog.html
> +              <img src="images\search-loop.svg" width="18.05" height="18.1">
убрал

2022-02-20 19:48 UTC, Artem-Olkhovoi commented on styles/styles.css
> +    font-family: "PT Sans";
установил

2022-02-20 19:56 UTC, Artem-Olkhovoi commented on styles/styles.css
> +    color: white;
всё исправил

2022-02-21 12:21 UTC, dean992008 commented on styles/styles.css
> +body {
Не ту ссылку прикрепил, имел виду эту: https://up.htmlacademy.ru/htmlcss/33/criteries#CSS-02.

2022-02-21 12:22 UTC, dean992008 commented on styles/styles.css
> +    font-family: "PT Sans";
Документ почему-то остался на 4 пробела отступа, нужно сделать 2.

2022-02-21 12:24 UTC, dean992008 commented on catalog.html
> +              <img src="images\search-loop.svg" width="18.05" height="18.1">
Не убрал в `index.html`. Нужно полностью убрать тег `img`, она будет добавлена через CSS.

2022-02-25 10:08 UTC, merged